# Site settings
name: Jayavardhan Karampudi
title: Jayavardhan | Back End Software Engineer
description: back-end software engineer working 'behind the scenes' building core logic & experiences
url: https://jayavardhan3112.github.io/
baseurl: 'https://jayavardhan3112.github.io/'
email: jayavardhan3112@gmail.com
cover: https://jayavardhan3112.github.io/img/og.png
logo: https://jayavardhan3112.github.io/img/emojis/glitter.png
resume: https://jayavardhan3112.github.io/Resume.pdf
social:
  - title: email
    url: mailto:jayavardhan3112@gmail.com
  - title: twitter
    url: https://twitter.com/thejayavardhan
  - title: instagram
    url: https://instagram.com/jai_3112
  - title: github
    url: https://github.com/jayavardhan3112
  - title: linkedin
    url: https://www.linkedin.com/in/jayavardhan3112

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

theme: jekyll-theme-hacker
